/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as WatchAnimeIdEpisodeNumberRouteImport } from './routes/watch.$animeId.$episodeNumber'
import { Route as WatchAnimeIdEpisodeIndexRouteImport } from './routes/watch.$animeId.$episodeIndex'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchAnimeIdEpisodeNumberRoute =
  WatchAnimeIdEpisodeNumberRouteImport.update({
    id: '/watch/$animeId/$episodeNumber',
    path: '/watch/$animeId/$episodeNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const WatchAnimeIdEpisodeIndexRoute =
  WatchAnimeIdEpisodeIndexRouteImport.update({
    id: '/watch/$animeId/$episodeIndex',
    path: '/watch/$animeId/$episodeIndex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$animeId/$episodeIndex': typeof WatchAnimeIdEpisodeIndexRoute
  '/watch/$animeId/$episodeNumber': typeof WatchAnimeIdEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$animeId/$episodeIndex': typeof WatchAnimeIdEpisodeIndexRoute
  '/watch/$animeId/$episodeNumber': typeof WatchAnimeIdEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$animeId/$episodeIndex': typeof WatchAnimeIdEpisodeIndexRoute
  '/watch/$animeId/$episodeNumber': typeof WatchAnimeIdEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/favorites'
    | '/anime/$id'
    | '/watch/$animeId/$episodeIndex'
    | '/watch/$animeId/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/favorites'
    | '/anime/$id'
    | '/watch/$animeId/$episodeIndex'
    | '/watch/$animeId/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/favorites'
    | '/anime/$id'
    | '/watch/$animeId/$episodeIndex'
    | '/watch/$animeId/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  FavoritesRoute: typeof FavoritesRoute
  AnimeIdRoute: typeof AnimeIdRoute
  WatchAnimeIdEpisodeIndexRoute: typeof WatchAnimeIdEpisodeIndexRoute
  WatchAnimeIdEpisodeNumberRoute: typeof WatchAnimeIdEpisodeNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$animeId/$episodeNumber': {
      id: '/watch/$animeId/$episodeNumber'
      path: '/watch/$animeId/$episodeNumber'
      fullPath: '/watch/$animeId/$episodeNumber'
      preLoaderRoute: typeof WatchAnimeIdEpisodeNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$animeId/$episodeIndex': {
      id: '/watch/$animeId/$episodeIndex'
      path: '/watch/$animeId/$episodeIndex'
      fullPath: '/watch/$animeId/$episodeIndex'
      preLoaderRoute: typeof WatchAnimeIdEpisodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  FavoritesRoute: FavoritesRoute,
  AnimeIdRoute: AnimeIdRoute,
  WatchAnimeIdEpisodeIndexRoute: WatchAnimeIdEpisodeIndexRoute,
  WatchAnimeIdEpisodeNumberRoute: WatchAnimeIdEpisodeNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
